### ISSUE TITLE
Chapter 5: Why you use useQuery than useLazyQuery when search users?

### ISSUE THREAD

**Issue by alrasyidin** [PacktPublishing/Full-Stack-Web-Development-with-GraphQL-and-React-Second-Edition#2]
What your reason or consideration using useQuery function than useLazyQuery, in my opinion we can apply keypress event and listen when user press 'Enter' ? I'm just curious how to implement user experience when use our app.

**Comment by devlinduldulao** [comment]
Hey @alrasyidin, the useQuery is faster because it gets data from the cache. The useLazyQuery is like an on-demand getting of data.
