### ISSUE TITLE
Nodemon crashes !!

### ISSUE THREAD

**Issue by swolfadder** [PacktPublishing/Full-Stack-Web-Development-with-GraphQL-and-React-Second-Edition#3]
I'm on page 151 now, and I have hit a real problem that I have searched for days, now while running nom run server, there is a error which crashes nodemon. 

``/models/index.js:19
  var context = require.context('.', true, /^\.\/(?!index\.js).*\.js$/, 'sync');``

``TypeError: require.context is not a function`` ??

caused by, 

`require('babel-plugin-require-context-hook/register')()` 

I haven't found a fix for this yet? can you help?

full code for index.js models

`import Sequelize from 'sequelize';

if (process.env.NODE_ENV === 'development') {
  require('babel-plugin-require-context-hook/register')()
}

export default (sequelize) => {
  let db = {};

  const context = require.context('.', true, /^\.\/(?!index\.js).*\.js$/, 'sync')

  context.keys().map(context).forEach(module => {
    const model = module(sequelize, Sequelize);
    db[model.name] = model;
  });

  Object.keys(db).forEach((modelName) => {
    if (db[modelName].associate) {
      db[modelName].associate(db);
    }
  });

  return db;
};`

I've also tried running in another chapter further ahead and back, still the same result. Please help me so I can finish your book!

**Comment by TBarmak** [comment]
Hi, did you make sure to set your NODE_ENV to development?

Try running `export NODE_ENV=development` first

**Comment by swolfadder** [comment]
Yes I tried that, believe it was already set as that , and also a few other suggested fixes I found online, still can’t get it to run, no matter what.

**Comment by KindEni** [comment]
I am also encountering the same error, right now

**Comment by KindEni** [comment]
Please have you found a fix for it yet

**Comment by esparkman** [comment]
Try adding this to your `scripts` in `package.json`
```js
"server": "NODE_ENV=development nodemon --exec babel-node --plugins @storybook/babel-plugin-require-context-hook --watch src/server/index.js"
```

**Comment by swolfadder** [comment]
> Please have you found a fix for it yet
> 
> 

I have not, but will try the recent posts suggestion

**Comment by KindEni** [comment]
> Try adding this to your `scripts` in `package.json`
> 
> ```js
> "server": "NODE_ENV=development nodemon --exec babel-node --plugins @storybook/babel-plugin-require-context-hook --watch src/server/index.js"
> ```
This is the result of the command, NODE_ENV is not recognised.
![Capture_1](https://user-images.githubusercontent.com/43914673/176672997-d948d01b-92f9-465a-b6a3-ae3ff6c71d4e.PNG)

**Comment by KindEni** [comment]
I have found a fixed!! i no longer get `[nodemon] crashed error`



Here are the steps:
Install the following packages:

-  `npm install --save-dev  @storybook/babel-plugin-require-context-hook`
- `npm install --save-dev  babel-plugin-transform-require-context`

- Create a `babel-hook.js` file in the root directory of your project, and write the code below. This file serves as an alternative to `babel.rc`

```javascript=
require("@babel/register")({
    "plugins": [
        "@storybook/babel-plugin-require-context-hook"
    ],
    "presets": ["@babel/env","babel/react"]
});

```
- Add the following script to your `package.json` file
`"server": "nodemon --exec babel-node --require @storybook/babel-plugin-require-context-hook --watch src/server src/server/index.js"`

- Finally change `require('babel-plugin-require-context-hook/register')();` to `require('@storybook/babel-plugin-require-context-hook/register')();`

Now run `npm run server` there should  be no more errors.

**Comment by swolfadder** [comment]
> Try adding this to your `scripts` in `package.json`
> 
> ```js
> "server": "NODE_ENV=development nodemon --exec babel-node --plugins @storybook/babel-plugin-require-context-hook --watch src/server/index.js"
> ```

This results with a babel > prompt, I'm not sure if that's the desired output, but it least it didn't crash lol, however in the browser now for the client, it just says "Load failed" which could be another problem, I'll have to further investigate , but thank you for the suggestion!

**Comment by sebastiangrebe** [comment]
Sorry for the late reply. Just saw this thread.

Does this problem occur by plainly copying the files from the repo here?

**Comment by swolfadder** [comment]
> Sorry for the late reply. Just saw this thread.
> 
> 
> 
> Does this problem occur by plainly copying the files from the repo here?

Yes even using the copying files error still occurs

**Comment by sebastiangrebe** [comment]
Can you confirm that you are using windows?

Maybe try this `set NODE_ENV=production&& nodemon` etc.

**Comment by swolfadder** [comment]
I was using a Mac at the time. You think the OS makes a difference in this case?

**Comment by sebastiangrebe** [comment]
At least the issue by @KindEni in the screenshot: https://github.com/PacktPublishing/Full-Stack-Web-Development-with-GraphQL-and-React-Second-Edition/issues/3#issuecomment-1171229639

As windows and mac pass env variables differently.

@ryancollins-dev can you give a full screenshot or stack trace for your issue?

**Comment by swolfadder** [comment]
Oh ok, I don’t have a mac anymore, so I’ll try again on windows and see if everything is ok. Thank you.

**Comment by sebastiangrebe** [comment]
Closing this as there was no further update, feel free to create a new issue if you still notice it
