### ISSUE TITLE
Code typo in book/github - Chapter03/src/server/services/graphql/resolvers.js 

### ISSUE THREAD

**Issue by NoLandMen496** [PacktPublishing/Full-Stack-Web-Development-with-GraphQL-and-React-Second-Edition#6]
First of all: Sebastian amazing book and app. Keep up with the good work. I have grown a lot as a developer because of you.

Line 98 on the file above should be changed from ```'Message was created'``` to ```'Chat was created'```.

All the chapters after chp3 probably need to be edited too on GitHub. Left this in case you want to write a third edition. Thanks.

**Comment by sebastiangrebe** [comment]
@NoLandMen496 thanks for pointing it out. I have updated all chapters :)

Thanks for pointing out and the feedback :)
